FROM node:20-alpine

RUN npm install -g pnpm

RUN mkdir /temp && cd /temp && pnpm create astro my-starlight --template starlight --yes

WORKDIR /app

RUN cp -r /temp/my-starlight/* /app/ && rm -rf /temp

COPY .astro-starlight/astro.config.mjs .
COPY .astro-starlight/mermaid-zoom.js ./public/

RUN pnpm install && pnpm add astro-mermaid mermaid

EXPOSE 4321

CMD ["pnpm", "dev", "--host", "0.0.0.0"]